repos:
  - repo: https://github.com/pycqa/pylint
    rev: v2.16.1
    hooks:
    - id: pylint
      args: [--rcfile=src/pylintrc]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
    - id: gitlint
      args: [--staged, --msg-filename]
      stages: [commit-msg]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black]
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
    - id: mypy
