name: Release to GitHub, PyPI and Docker Hub
on:
  workflow_dispatch:

env:
  gh-release-user-name: Ely Deckers
  python-version: 3.9

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish release
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
          architecture: x64
      - run: make release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RELEASE_USER_EMAIL: ${{ secrets.GH_RELEASE_USER_EMAIL }}
          GITHUB_RELEASE_USER_NAME: ${{ env.gh-release-user-name }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN}}
