name: Release to GitHub, PyPI and Docker Hub
on:
  workflow_dispatch:

env:
  github-release-user-name: Ely Deckers
  python-version: 3.8

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish release
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
          architecture: x64
      - run: make release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RELEASE_USER_EMAIL: ${{ secrets.GITHUB_RELEASE_USER_EMAIL }}
          GITHUB_RELEASE_USER_NAME: ${{ env.github-release-user-name }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN}}
